#!/usr/bin/env bash

if [[ $(git rev-parse --show-toplevel) != $(pwd) ]]; then
  echo "Error: Not in root directory"
  exit 1
fi

# Generate pom file
clj -Spom
clj -Abuild

# Verify that repo isn't dirty
if [[ $(git diff --stat) != '' ]]; then
  echo "Error: dirty repo"
  exit 1
fi

# Replace HEAD with git sha
sed -i.bak "s/HEAD/$(git rev-parse HEAD)/g" pom.xml && rm pom.xml.bak
sed -i.bak "s/\n//g" pom.xml && rm pom.xml.bak

# Generate jar file
rm -f whiskey.jar
clj -Apack

# Upload to clojars
mvn deploy

sed -i.bak "s/$(git rev-parse HEAD)/HEAD/g" pom.xml && rm pom.xml.bak
