#!/usr/bin/env bash

if [[ $(git diff --stat) != '' ]]; then
  echo "Error: dirty repo"
  exit 1
elif [[ $(git rev-parse --show-toplevel) != $(pwd) ]]; then
  echo "Error: Not in root directory"
  exit 1
elif [ -z "$CLOJARS_USERNAME" ]; then
  echo "Error: CLOJARS_USERNAME is empty"
  exit 1
elif [ -z "$CLOJARS_PASSWORD" ]; then
  echo "Error: CLOJARS_PASSWORD is empty"
  exit 1
fi

# Generate pom file
clj -Spom

sed -i "s/HEAD/$(git rev-parse HEAD)/g" pom.xml

# Generate jar file
rm -f whiskey.jar
clj -Apack

# Upload to clojars
clj -Adeploy

sed -i "s/$(git rev-parse HEAD)/HEAD/g" pom.xml
